all:
  hosts:
    localhost:
      connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    db2:
      ansible_host: 192.168.1.54
      ansible_user: ubuntu
      ansible_python_interpreter: /usr/bin/python3
  vars:
    versions:
      postgres: 10
  children:
    ubuntu:
      hosts:
        db2:
    postgres:
      hosts:
        db2:
